# Generated by Django 6.0.3 on 2026-04-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Listing',
        ),
    ]
