# Generated by Django 6.0.3 on 2026-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_category_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
