# Generated by Django 6.0.6 on 2026-06-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bid',
            name='auctions_bi_listing_2da8f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='auctions_co_listing_3c6c4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchlist',
            name='auctions_wa_user_id_541cfe_idx',
        ),
    ]
